=== Pepech97/LenguajeMarcas2EV/COSAS_PARA_EXAMEN/PruebaRepaso2EVA/Pruebarepasoxsd.xsd
<?xml version = "1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ticket">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="datos_ticket">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="fecha_hora" type="xs:dateTime"/>
              <xs:element name="precio_total">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="cantidad_sin_iva" type="xs:int"/>
                    <xs:element name="cantidad_iva" type="xs:int"/>
                    <xs:element name="pvp_total" type="xs:int"/>
                  </xs:sequence>
                  <xs:attribute name="moneda" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="forma_pago">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="numero" type="xs:string"/>
                      <xs:attribute name="tipo" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="cliente" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="datos_comercio">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="direccion" type="xs:string"/>
              <xs:element name="cif" type="xs:string"/>
              <xs:element name="telefono" type="xs:int"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="datos_compra">
          <xs:complexType>
            <xs:sequence>
            <xs:element name="lineas_compra">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="nombre_articulo" type="xs:string"/>
                  <xs:element name="cantidad" type="xs:int"/>
                  <xs:element name="precio_unitario" type="xs:int"/>
                  <xs:element name="iva" type="xs:int"/>
                  <xs:element name="pvp" type="xs:int"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="codigo" type="xs:ID" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Pepech97/LenguajeMarcas2EV/COSAS_PARA_EXAMEN/PruebaRepaso2EVA/Pruebarepasoxml.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<ticket codigo="t00037" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="Pruebarepasoxsd.xsd">
<datos_ticket>
  <fecha_hora>1998-07-12T16:30:00.000</fecha_hora>
	<precio_total moneda="euro">
		<cantidad_sin_iva>1</cantidad_sin_iva>
		<cantidad_iva>1</cantidad_iva>
		<pvp_total>1</pvp_total>
	</precio_total>
	<forma_pago numero="************1234" tipo="Visa Clasica">
	Tarjeta
	</forma_pago>
	<cliente>Pedro Medario</cliente>
</datos_ticket>
<datos_comercio>
	<nombre></nombre>
	<direccion></direccion>
	<cif></cif>
	<telefono>1</telefono>
</datos_comercio>
<datos_compra>
	<lineas_compra>
		<nombre_articulo></nombre_articulo>
		<cantidad>1</cantidad>
		<precio_unitario>1</precio_unitario>
		<iva>1</iva>
		<pvp>1</pvp>
	</lineas_compra>
</datos_compra>
</ticket>
